package com.ipr.entity.other;
// Generated 26 Dec, 2018 5:16:16 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.ipr.entity.AppUser;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "ipr_data", uniqueConstraints = { @UniqueConstraint(columnNames = "mail_id"),
		@UniqueConstraint(columnNames = "website") })
public class Account implements java.io.Serializable {

	private long id;
	private AppUser appUser;
	private String accountName;
	private String mailId;
	private Long contact;
	private String address;
	private String website;
	private Date createdDate;

	public Account() {
	}

	public Account(long id, AppUser appUser) {
		this.id = id;
		this.appUser = appUser;
	}

	public Account(long id, AppUser appUser, String accountName, String mailId, Long contact, String address,
			String website, Date createdDate) {
		this.id = id;
		this.appUser = appUser;
		this.accountName = accountName;
		this.mailId = mailId;
		this.contact = contact;
		this.address = address;
		this.website = website;
		this.createdDate = createdDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}

	@Column(name = "account_name", length = 250)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "mail_id", unique = true, length = 250)
	public String getMailId() {
		return this.mailId;
	}

	public void setMailId(String mailId) {
		this.mailId = mailId;
	}

	@Column(name = "contact")
	public Long getContact() {
		return this.contact;
	}

	public void setContact(Long contact) {
		this.contact = contact;
	}

	@Column(name = "address", length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "website", unique = true, length = 250)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
