package com.ipr.entity.other;
// Generated 3 Jan, 2019 3:16:32 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProjectTypes generated by hbm2java
 */
@Entity
@Table(name = "project_types", catalog = "ipr_data", uniqueConstraints = @UniqueConstraint(columnNames = "project_type"))
public class ProjectTypes implements java.io.Serializable {

	private int id;
	private String projectType;
	private Set<Project> projects = new HashSet<>(0);

	public ProjectTypes() {
	}

	public ProjectTypes(int id, String projectType) {
		this.id = id;
		this.projectType = projectType;
	}

	public ProjectTypes(int id, String projectType, Set<Project>projects) {
		this.id = id;
		this.projectType = projectType;
		this.projects = projects;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "project_type", unique = true, nullable = false, length = 50)
	public String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(String projectType) {
		this.projectType = projectType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectTypes")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
