package com.ipr.entity.other;
// Generated 26 Dec, 2018 5:16:16 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "ipr_data", uniqueConstraints = @UniqueConstraint(columnNames = "project_url"))
public class Project implements java.io.Serializable {

	private long id;
	private int projectTypesId;
	private long accountId;
	private String projectName;
	private String channelName;
	private String projectUrl;
	private String contractUrl;
	private Long createdBy;
	private Date createdTime;
	private byte deactivate;
	private Long deactivatedBy;
	private Date deactivatedDate;

	public Project() {
	}

	public Project(long id, int projectTypesId, long accountId, Date createdTime, byte deactivate) {
		this.id = id;
		this.projectTypesId = projectTypesId;
		this.accountId = accountId;
		this.createdTime = createdTime;
		this.deactivate = deactivate;
	}

	public Project(long id, int projectTypesId, long accountId, String projectName, String channelName,
			String projectUrl, String contractUrl, Long createdBy, Date createdTime, byte deactivate,
			Long deactivatedBy, Date deactivatedDate) {
		this.id = id;
		this.projectTypesId = projectTypesId;
		this.accountId = accountId;
		this.projectName = projectName;
		this.channelName = channelName;
		this.projectUrl = projectUrl;
		this.contractUrl = contractUrl;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.deactivate = deactivate;
		this.deactivatedBy = deactivatedBy;
		this.deactivatedDate = deactivatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "project_types_id", nullable = false)
	public int getProjectTypesId() {
		return this.projectTypesId;
	}

	public void setProjectTypesId(int projectTypesId) {
		this.projectTypesId = projectTypesId;
	}

	@Column(name = "account_id", nullable = false)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "project_name", length = 250)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "channel_name", length = 250)
	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	@Column(name = "project_url", unique = true, length = 250)
	public String getProjectUrl() {
		return this.projectUrl;
	}

	public void setProjectUrl(String projectUrl) {
		this.projectUrl = projectUrl;
	}

	@Column(name = "contract_url", length = 250)
	public String getContractUrl() {
		return this.contractUrl;
	}

	public void setContractUrl(String contractUrl) {
		this.contractUrl = contractUrl;
	}

	@Column(name = "created_by")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "deactivate", nullable = false)
	public byte getDeactivate() {
		return this.deactivate;
	}

	public void setDeactivate(byte deactivate) {
		this.deactivate = deactivate;
	}

	@Column(name = "deactivated_by")
	public Long getDeactivatedBy() {
		return this.deactivatedBy;
	}

	public void setDeactivatedBy(Long deactivatedBy) {
		this.deactivatedBy = deactivatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deactivated_date", length = 19)
	public Date getDeactivatedDate() {
		return this.deactivatedDate;
	}

	public void setDeactivatedDate(Date deactivatedDate) {
		this.deactivatedDate = deactivatedDate;
	}

}
