package com.ipr.entity.other;
// Generated 26 Dec, 2018 5:16:16 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UploadDataViewOmqcId generated by hbm2java
 */
@Embeddable
public class UploadDataViewOmqcId implements java.io.Serializable {

	private long id;
	private String link;
	private String domainName;
	private String sourceLink;
	private long projectId;
	private String projectName;
	private String channelName;
	private String projectUrl;
	private String projectType;
	private String accountName;
	private Integer userId;
	private String userFirstName;
	private String userLastName;

	public UploadDataViewOmqcId() {
	}

	public UploadDataViewOmqcId(long id, String link, String domainName, String sourceLink, long projectId,
			String projectType) {
		this.id = id;
		this.link = link;
		this.domainName = domainName;
		this.sourceLink = sourceLink;
		this.projectId = projectId;
		this.projectType = projectType;
	}

	public UploadDataViewOmqcId(long id, String link, String domainName, String sourceLink, long projectId,
			String projectName, String channelName, String projectUrl, String projectType, String accountName,
			Integer userId, String userFirstName, String userLastName) {
		this.id = id;
		this.link = link;
		this.domainName = domainName;
		this.sourceLink = sourceLink;
		this.projectId = projectId;
		this.projectName = projectName;
		this.channelName = channelName;
		this.projectUrl = projectUrl;
		this.projectType = projectType;
		this.accountName = accountName;
		this.userId = userId;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "link", nullable = false, length = 250)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "domain_name", nullable = false, length = 50)
	public String getDomainName() {
		return this.domainName;
	}

	public void setDomainName(String domainName) {
		this.domainName = domainName;
	}

	@Column(name = "source_link", nullable = false, length = 250)
	public String getSourceLink() {
		return this.sourceLink;
	}

	public void setSourceLink(String sourceLink) {
		this.sourceLink = sourceLink;
	}

	@Column(name = "project_id", nullable = false)
	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

	@Column(name = "project_name", length = 250)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "channel_name", length = 250)
	public String getChannelName() {
		return this.channelName;
	}

	public void setChannelName(String channelName) {
		this.channelName = channelName;
	}

	@Column(name = "project_url", length = 250)
	public String getProjectUrl() {
		return this.projectUrl;
	}

	public void setProjectUrl(String projectUrl) {
		this.projectUrl = projectUrl;
	}

	@Column(name = "project_type", nullable = false, length = 50)
	public String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(String projectType) {
		this.projectType = projectType;
	}

	@Column(name = "account_name", length = 250)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_first_name", length = 50)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	@Column(name = "user_last_name", length = 50)
	public String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UploadDataViewOmqcId))
			return false;
		UploadDataViewOmqcId castOther = (UploadDataViewOmqcId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getLink() == castOther.getLink()) || (this.getLink() != null && castOther.getLink() != null
						&& this.getLink().equals(castOther.getLink())))
				&& ((this.getDomainName() == castOther.getDomainName()) || (this.getDomainName() != null
						&& castOther.getDomainName() != null && this.getDomainName().equals(castOther.getDomainName())))
				&& ((this.getSourceLink() == castOther.getSourceLink()) || (this.getSourceLink() != null
						&& castOther.getSourceLink() != null && this.getSourceLink().equals(castOther.getSourceLink())))
				&& (this.getProjectId() == castOther.getProjectId())
				&& ((this.getProjectName() == castOther.getProjectName())
						|| (this.getProjectName() != null && castOther.getProjectName() != null
								&& this.getProjectName().equals(castOther.getProjectName())))
				&& ((this.getChannelName() == castOther.getChannelName())
						|| (this.getChannelName() != null && castOther.getChannelName() != null
								&& this.getChannelName().equals(castOther.getChannelName())))
				&& ((this.getProjectUrl() == castOther.getProjectUrl()) || (this.getProjectUrl() != null
						&& castOther.getProjectUrl() != null && this.getProjectUrl().equals(castOther.getProjectUrl())))
				&& ((this.getProjectType() == castOther.getProjectType())
						|| (this.getProjectType() != null && castOther.getProjectType() != null
								&& this.getProjectType().equals(castOther.getProjectType())))
				&& ((this.getAccountName() == castOther.getAccountName())
						|| (this.getAccountName() != null && castOther.getAccountName() != null
								&& this.getAccountName().equals(castOther.getAccountName())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserFirstName() == castOther.getUserFirstName())
						|| (this.getUserFirstName() != null && castOther.getUserFirstName() != null
								&& this.getUserFirstName().equals(castOther.getUserFirstName())))
				&& ((this.getUserLastName() == castOther.getUserLastName())
						|| (this.getUserLastName() != null && castOther.getUserLastName() != null
								&& this.getUserLastName().equals(castOther.getUserLastName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (getLink() == null ? 0 : this.getLink().hashCode());
		result = 37 * result + (getDomainName() == null ? 0 : this.getDomainName().hashCode());
		result = 37 * result + (getSourceLink() == null ? 0 : this.getSourceLink().hashCode());
		result = 37 * result + (int) this.getProjectId();
		result = 37 * result + (getProjectName() == null ? 0 : this.getProjectName().hashCode());
		result = 37 * result + (getChannelName() == null ? 0 : this.getChannelName().hashCode());
		result = 37 * result + (getProjectUrl() == null ? 0 : this.getProjectUrl().hashCode());
		result = 37 * result + (getProjectType() == null ? 0 : this.getProjectType().hashCode());
		result = 37 * result + (getAccountName() == null ? 0 : this.getAccountName().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getUserFirstName() == null ? 0 : this.getUserFirstName().hashCode());
		result = 37 * result + (getUserLastName() == null ? 0 : this.getUserLastName().hashCode());
		return result;
	}

}
