package com.ipr.entity.other;
// Generated 28 Dec, 2018 2:44:56 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UploadDataActionId generated by hbm2java
 */
@Embeddable
public class UploadDataActionId implements java.io.Serializable {

	private Long uploadDataId;
	private byte directNotice;
	private byte invalid;
	private long invalidBy;
	private Date invalidDate;
	private String invalidReason;
	private byte qc1;
	private Integer qc1User;
	private Date qc1Time;
	private byte qc2;
	private Integer qc2User;
	private Date qc2Time;
	private byte dataNotify;
	private int dataNotifyUser;
	private byte fourceNotify;

	public UploadDataActionId() {
	}

	public UploadDataActionId(byte directNotice, byte invalid, long invalidBy, byte qc1, byte qc2, byte dataNotify,
			int dataNotifyUser, byte fourceNotify) {
		this.directNotice = directNotice;
		this.invalid = invalid;
		this.invalidBy = invalidBy;
		this.qc1 = qc1;
		this.qc2 = qc2;
		this.dataNotify = dataNotify;
		this.dataNotifyUser = dataNotifyUser;
		this.fourceNotify = fourceNotify;
	}

	public UploadDataActionId(Long uploadDataId, byte directNotice, byte invalid, long invalidBy, Date invalidDate,
			String invalidReason, byte qc1, Integer qc1User, Date qc1Time, byte qc2, Integer qc2User, Date qc2Time,
			byte dataNotify, int dataNotifyUser, byte fourceNotify) {
		this.uploadDataId = uploadDataId;
		this.directNotice = directNotice;
		this.invalid = invalid;
		this.invalidBy = invalidBy;
		this.invalidDate = invalidDate;
		this.invalidReason = invalidReason;
		this.qc1 = qc1;
		this.qc1User = qc1User;
		this.qc1Time = qc1Time;
		this.qc2 = qc2;
		this.qc2User = qc2User;
		this.qc2Time = qc2Time;
		this.dataNotify = dataNotify;
		this.dataNotifyUser = dataNotifyUser;
		this.fourceNotify = fourceNotify;
	}

	@Column(name = "upload_data_id", unique = true)
	public Long getUploadDataId() {
		return this.uploadDataId;
	}

	public void setUploadDataId(Long uploadDataId) {
		this.uploadDataId = uploadDataId;
	}

	@Column(name = "direct_notice", nullable = false)
	public byte getDirectNotice() {
		return this.directNotice;
	}

	public void setDirectNotice(byte directNotice) {
		this.directNotice = directNotice;
	}

	@Column(name = "invalid", nullable = false)
	public byte getInvalid() {
		return this.invalid;
	}

	public void setInvalid(byte invalid) {
		this.invalid = invalid;
	}

	@Column(name = "invalid_by", nullable = false)
	public long getInvalidBy() {
		return this.invalidBy;
	}

	public void setInvalidBy(long invalidBy) {
		this.invalidBy = invalidBy;
	}

	@Column(name = "invalid_date", length = 19)
	public Date getInvalidDate() {
		return this.invalidDate;
	}

	public void setInvalidDate(Date invalidDate) {
		this.invalidDate = invalidDate;
	}

	@Column(name = "invalid_reason", length = 250)
	public String getInvalidReason() {
		return this.invalidReason;
	}

	public void setInvalidReason(String invalidReason) {
		this.invalidReason = invalidReason;
	}

	@Column(name = "qc1", nullable = false)
	public byte getQc1() {
		return this.qc1;
	}

	public void setQc1(byte qc1) {
		this.qc1 = qc1;
	}

	@Column(name = "qc1_user")
	public Integer getQc1User() {
		return this.qc1User;
	}

	public void setQc1User(Integer qc1User) {
		this.qc1User = qc1User;
	}

	@Column(name = "qc1_time", length = 19)
	public Date getQc1Time() {
		return this.qc1Time;
	}

	public void setQc1Time(Date qc1Time) {
		this.qc1Time = qc1Time;
	}

	@Column(name = "qc2", nullable = false)
	public byte getQc2() {
		return this.qc2;
	}

	public void setQc2(byte qc2) {
		this.qc2 = qc2;
	}

	@Column(name = "qc2_user")
	public Integer getQc2User() {
		return this.qc2User;
	}

	public void setQc2User(Integer qc2User) {
		this.qc2User = qc2User;
	}

	@Column(name = "qc2_time", length = 19)
	public Date getQc2Time() {
		return this.qc2Time;
	}

	public void setQc2Time(Date qc2Time) {
		this.qc2Time = qc2Time;
	}

	@Column(name = "data_Notify", nullable = false)
	public byte getDataNotify() {
		return this.dataNotify;
	}

	public void setDataNotify(byte dataNotify) {
		this.dataNotify = dataNotify;
	}

	@Column(name = "data_notify_user", nullable = false)
	public int getDataNotifyUser() {
		return this.dataNotifyUser;
	}

	public void setDataNotifyUser(int dataNotifyUser) {
		this.dataNotifyUser = dataNotifyUser;
	}

	@Column(name = "fource_notify", nullable = false)
	public byte getFourceNotify() {
		return this.fourceNotify;
	}

	public void setFourceNotify(byte fourceNotify) {
		this.fourceNotify = fourceNotify;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UploadDataActionId))
			return false;
		UploadDataActionId castOther = (UploadDataActionId) other;

		return ((this.getUploadDataId() == castOther.getUploadDataId()) || (this.getUploadDataId() != null
				&& castOther.getUploadDataId() != null && this.getUploadDataId().equals(castOther.getUploadDataId())))
				&& (this.getDirectNotice() == castOther.getDirectNotice())
				&& (this.getInvalid() == castOther.getInvalid()) && (this.getInvalidBy() == castOther.getInvalidBy())
				&& ((this.getInvalidDate() == castOther.getInvalidDate())
						|| (this.getInvalidDate() != null && castOther.getInvalidDate() != null
								&& this.getInvalidDate().equals(castOther.getInvalidDate())))
				&& ((this.getInvalidReason() == castOther.getInvalidReason())
						|| (this.getInvalidReason() != null && castOther.getInvalidReason() != null
								&& this.getInvalidReason().equals(castOther.getInvalidReason())))
				&& (this.getQc1() == castOther.getQc1())
				&& ((this.getQc1User() == castOther.getQc1User()) || (this.getQc1User() != null
						&& castOther.getQc1User() != null && this.getQc1User().equals(castOther.getQc1User())))
				&& ((this.getQc1Time() == castOther.getQc1Time()) || (this.getQc1Time() != null
						&& castOther.getQc1Time() != null && this.getQc1Time().equals(castOther.getQc1Time())))
				&& (this.getQc2() == castOther.getQc2())
				&& ((this.getQc2User() == castOther.getQc2User()) || (this.getQc2User() != null
						&& castOther.getQc2User() != null && this.getQc2User().equals(castOther.getQc2User())))
				&& ((this.getQc2Time() == castOther.getQc2Time()) || (this.getQc2Time() != null
						&& castOther.getQc2Time() != null && this.getQc2Time().equals(castOther.getQc2Time())))
				&& (this.getDataNotify() == castOther.getDataNotify())
				&& (this.getDataNotifyUser() == castOther.getDataNotifyUser())
				&& (this.getFourceNotify() == castOther.getFourceNotify());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUploadDataId() == null ? 0 : this.getUploadDataId().hashCode());
		result = 37 * result + this.getDirectNotice();
		result = 37 * result + this.getInvalid();
		result = 37 * result + (int) this.getInvalidBy();
		result = 37 * result + (getInvalidDate() == null ? 0 : this.getInvalidDate().hashCode());
		result = 37 * result + (getInvalidReason() == null ? 0 : this.getInvalidReason().hashCode());
		result = 37 * result + this.getQc1();
		result = 37 * result + (getQc1User() == null ? 0 : this.getQc1User().hashCode());
		result = 37 * result + (getQc1Time() == null ? 0 : this.getQc1Time().hashCode());
		result = 37 * result + this.getQc2();
		result = 37 * result + (getQc2User() == null ? 0 : this.getQc2User().hashCode());
		result = 37 * result + (getQc2Time() == null ? 0 : this.getQc2Time().hashCode());
		result = 37 * result + this.getDataNotify();
		result = 37 * result + this.getDataNotifyUser();
		result = 37 * result + this.getFourceNotify();
		return result;
	}

}
