package com.ipr.entity.other;
// Generated 3 Jan, 2019 3:16:32 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UploadDataAction generated by hbm2java
 */
@Entity
@Table(name = "upload_data_action", catalog = "ipr_data", uniqueConstraints = @UniqueConstraint(columnNames = "upload_data_id"))
public class UploadDataAction implements java.io.Serializable {

	private UploadDataActionId id;

	public UploadDataAction() {
	}

	public UploadDataAction(UploadDataActionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "uploadDataId", column = @Column(name = "upload_data_id", unique = true)),
			@AttributeOverride(name = "directNotice", column = @Column(name = "direct_notice", nullable = false)),
			@AttributeOverride(name = "invalid", column = @Column(name = "invalid", nullable = false)),
			@AttributeOverride(name = "invalidBy", column = @Column(name = "invalid_by", nullable = false)),
			@AttributeOverride(name = "invalidDate", column = @Column(name = "invalid_date", length = 19)),
			@AttributeOverride(name = "invalidReason", column = @Column(name = "invalid_reason", length = 250)),
			@AttributeOverride(name = "qc1", column = @Column(name = "qc1", nullable = false)),
			@AttributeOverride(name = "qc1User", column = @Column(name = "qc1_user")),
			@AttributeOverride(name = "qc1Time", column = @Column(name = "qc1_time", length = 19)),
			@AttributeOverride(name = "qc2", column = @Column(name = "qc2", nullable = false)),
			@AttributeOverride(name = "qc2User", column = @Column(name = "qc2_user")),
			@AttributeOverride(name = "qc2Time", column = @Column(name = "qc2_time", length = 19)),
			@AttributeOverride(name = "dataNotify", column = @Column(name = "data_Notify", nullable = false)),
			@AttributeOverride(name = "dataNotifyUser", column = @Column(name = "data_notify_user", nullable = false)),
			@AttributeOverride(name = "fourceNotify", column = @Column(name = "fource_notify", nullable = false)) })
	public UploadDataActionId getId() {
		return this.id;
	}

	public void setId(UploadDataActionId id) {
		this.id = id;
	}

}
