package com.ipr.entity.other;
// Generated 3 Jan, 2019 3:16:32 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserPerformanceDetect generated by hbm2java
 */
@Entity
@Table(name = "user_performance_detect", catalog = "ipr_data", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "work_date" }))
public class UserPerformanceDetect implements java.io.Serializable {

	private long id;
	private Integer userId;
	private Date workDate;
	private int infringingCount;
	private int sourceCount;
	private int ytCount;
	private int fbCount;
	private int instaCount;
	private int twitterCount;
	private int wlCount;
	private int glCount;
	private int invalidCount;
	private int duplicateCount;

	public UserPerformanceDetect() {
	}

	public UserPerformanceDetect(long id, int infringingCount, int sourceCount, int ytCount, int fbCount,
			int instaCount, int twitterCount, int wlCount, int glCount, int invalidCount, int duplicateCount) {
		this.id = id;
		this.infringingCount = infringingCount;
		this.sourceCount = sourceCount;
		this.ytCount = ytCount;
		this.fbCount = fbCount;
		this.instaCount = instaCount;
		this.twitterCount = twitterCount;
		this.wlCount = wlCount;
		this.glCount = glCount;
		this.invalidCount = invalidCount;
		this.duplicateCount = duplicateCount;
	}

	public UserPerformanceDetect(long id, Integer userId, Date workDate, int infringingCount, int sourceCount,
			int ytCount, int fbCount, int instaCount, int twitterCount, int wlCount, int glCount, int invalidCount,
			int duplicateCount) {
		this.id = id;
		this.userId = userId;
		this.workDate = workDate;
		this.infringingCount = infringingCount;
		this.sourceCount = sourceCount;
		this.ytCount = ytCount;
		this.fbCount = fbCount;
		this.instaCount = instaCount;
		this.twitterCount = twitterCount;
		this.wlCount = wlCount;
		this.glCount = glCount;
		this.invalidCount = invalidCount;
		this.duplicateCount = duplicateCount;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "work_date", length = 10)
	public Date getWorkDate() {
		return this.workDate;
	}

	public void setWorkDate(Date workDate) {
		this.workDate = workDate;
	}

	@Column(name = "infringing_count", nullable = false)
	public int getInfringingCount() {
		return this.infringingCount;
	}

	public void setInfringingCount(int infringingCount) {
		this.infringingCount = infringingCount;
	}

	@Column(name = "source_count", nullable = false)
	public int getSourceCount() {
		return this.sourceCount;
	}

	public void setSourceCount(int sourceCount) {
		this.sourceCount = sourceCount;
	}

	@Column(name = "yt_count", nullable = false)
	public int getYtCount() {
		return this.ytCount;
	}

	public void setYtCount(int ytCount) {
		this.ytCount = ytCount;
	}

	@Column(name = "fb_count", nullable = false)
	public int getFbCount() {
		return this.fbCount;
	}

	public void setFbCount(int fbCount) {
		this.fbCount = fbCount;
	}

	@Column(name = "insta_count", nullable = false)
	public int getInstaCount() {
		return this.instaCount;
	}

	public void setInstaCount(int instaCount) {
		this.instaCount = instaCount;
	}

	@Column(name = "twitter_count", nullable = false)
	public int getTwitterCount() {
		return this.twitterCount;
	}

	public void setTwitterCount(int twitterCount) {
		this.twitterCount = twitterCount;
	}

	@Column(name = "wl_count", nullable = false)
	public int getWlCount() {
		return this.wlCount;
	}

	public void setWlCount(int wlCount) {
		this.wlCount = wlCount;
	}

	@Column(name = "gl_count", nullable = false)
	public int getGlCount() {
		return this.glCount;
	}

	public void setGlCount(int glCount) {
		this.glCount = glCount;
	}

	@Column(name = "invalid_count", nullable = false)
	public int getInvalidCount() {
		return this.invalidCount;
	}

	public void setInvalidCount(int invalidCount) {
		this.invalidCount = invalidCount;
	}

	@Column(name = "duplicate_count", nullable = false)
	public int getDuplicateCount() {
		return this.duplicateCount;
	}

	public void setDuplicateCount(int duplicateCount) {
		this.duplicateCount = duplicateCount;
	}

}
