package com.ipr.entity.other;
// Generated 3 Jan, 2019 3:16:32 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserPerformanceNotice generated by hbm2java
 */
@Entity
@Table(name = "user_performance_notice", catalog = "ipr_data")
public class UserPerformanceNotice implements java.io.Serializable {

	private long column1;

	public UserPerformanceNotice() {
	}

	public UserPerformanceNotice(long column1) {
		this.column1 = column1;
	}

	@Id

	@Column(name = "Column 1", unique = true, nullable = false)
	public long getColumn1() {
		return this.column1;
	}

	public void setColumn1(long column1) {
		this.column1 = column1;
	}

}
